version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./conf.d:/etc/nginx/conf.d