name: deploy to DigitalOcean
on:
  push:
    branches:
      - "main"
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: to-digitalocean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            mkdir /docker
            git clone git@github.com:warnshun/digital-ocean-nginx.git /docker/nginx
            cd /docker/nginx
            git fetch
            git reset origin/main --hard
            docker-compose down
            docker-compose up -d
            echo 'Deployment successful to Digital Ocean'
